# Generated by Django 2.0.7 on 2018-07-12 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='re_twit',
            field=models.ManyToManyField(related_name='retwit', to=settings.AUTH_USER_MODEL, verbose_name='Ретвит'),
        ),
    ]
